"""remove cancellation_token

Revision ID: 3855a4d7f1dc
Revises: 7caa2291ddd6
Create Date: 2026-06-07 19:43:19.755068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3855a4d7f1dc'
down_revision: Union[str, Sequence[str], None] = '7caa2291ddd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_cancellation_token_key'), 'appointments', type_='unique')
    op.drop_column('appointments', 'cancellation_token')
    op.drop_index(op.f('ix_clients_license_plate'), table_name='clients')
    op.create_unique_constraint(None, 'clients', ['license_plate'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_index(op.f('ix_clients_license_plate'), 'clients', ['license_plate'], unique=False)
    op.add_column('appointments', sa.Column('cancellation_token', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('appointments_cancellation_token_key'), 'appointments', ['cancellation_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
